[package]
name = "chaos-game-3d"
version = "0.1.0"
authors = ["Peter Gagliardi <ptrgags@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
json = "0.12.4"
